# Generated by Django 5.1.15 on 2026-06-09 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_alertu', models.CharField(choices=[('docelowy', 'Cena docelowa'), ('spadek_ceny', 'Procentowy spadek ceny'), ('flash_sale', 'Flash sale (auto)')], max_length=20)),
                ('prog_ceny', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('prog_procent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('aktywny', models.BooleanField(default=True)),
                ('ostatnie_wyzwolenie', models.DateTimeField(blank=True, null=True)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerty', to='groups.grupaproduktow')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerty',
                'db_table': 'alerty',
                'ordering': ['-utworzono'],
                'indexes': [models.Index(fields=['grupa'], name='idx_alerty_grupa'), models.Index(condition=models.Q(('aktywny', True)), fields=['aktywny'], name='idx_alerty_aktywne')],
            },
        ),
    ]
