# Generated by Django 5.1.15 on 2026-06-09 15:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprzedawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zewnetrzny_id', models.CharField(blank=True, max_length=255)),
                ('nazwa', models.CharField(max_length=255)),
                ('url_profilu', models.TextField(blank=True)),
                ('ocena', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('platforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprzedawcy', to='products.platforma')),
            ],
            options={
                'verbose_name': 'sprzedawca',
                'verbose_name_plural': 'sprzedawcy',
                'db_table': 'sprzedawcy',
                'indexes': [models.Index(fields=['platforma'], name='idx_sprzedawcy_platforma')],
                'constraints': [models.UniqueConstraint(fields=('platforma', 'zewnetrzny_id'), name='unique_sprzedawca_per_platforma'), models.CheckConstraint(condition=models.Q(('ocena__isnull', True), models.Q(('ocena__gte', 0), ('ocena__lte', 5)), _connector='OR'), name='ocena_w_zakresie')],
            },
        ),
    ]
