# Generated by Django 5.1.15 on 2026-06-09 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupaProduktow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True)),
                ('url_obrazka', models.TextField(blank=True)),
                ('najnizsza_cena_globalna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('najlepsza_platforma', models.CharField(blank=True, max_length=100)),
                ('najlepszy_sprzedawca', models.CharField(blank=True, max_length=255)),
                ('cena_docelowa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aktywny', models.BooleanField(default=True)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupa produktów',
                'verbose_name_plural': 'grupy produktów',
                'db_table': 'grupy_produktow',
                'ordering': ['-utworzono'],
                'indexes': [models.Index(fields=['uzytkownik'], name='idx_grupy_uzytkownik'), models.Index(condition=models.Q(('aktywny', True)), fields=['aktywny'], name='idx_grupy_aktywny')],
            },
        ),
    ]
