# Generated by Django 5.1.15 on 2026-06-09 15:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('bazowy_url', models.CharField(blank=True, max_length=255)),
                ('typ_scrapera', models.CharField(choices=[('api', 'API'), ('web', 'Web scraping')], max_length=20)),
            ],
            options={
                'verbose_name': 'platforma',
                'verbose_name_plural': 'platformy',
                'db_table': 'platformy',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zewnetrzny_id', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('nazwa', models.CharField(blank=True, max_length=500)),
                ('url_obrazka', models.TextField(blank=True)),
                ('aktywny', models.BooleanField(default=True)),
                ('wskaznik_zmiennosci', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('interwal_sprawdzania_min', models.PositiveIntegerField(default=360)),
                ('ostatnie_sprawdzenie', models.DateTimeField(blank=True, null=True)),
                ('nastepne_sprawdzenie', models.DateTimeField(blank=True, null=True)),
                ('aktualna_najnizsza_cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aktualny_najlepszy_sprzedawca', models.CharField(blank=True, max_length=255)),
                ('srednia_cena_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odchylenie_std_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('liczba_sprzedawcow', models.PositiveIntegerField(default=0)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='groups.grupaproduktow')),
                ('platforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produkty', to='products.platforma')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
                'db_table': 'produkty',
                'indexes': [models.Index(fields=['grupa'], name='produkty_grupa_i_02b298_idx'), models.Index(fields=['platforma'], name='produkty_platfor_82db20_idx'), models.Index(fields=['nastepne_sprawdzenie'], name='idx_produkty_polling'), models.Index(fields=['wskaznik_zmiennosci'], name='idx_produkty_volatility')],
                'constraints': [models.UniqueConstraint(fields=('grupa', 'platforma', 'zewnetrzny_id'), name='unique_produkt_per_platforma_w_grupie'), models.CheckConstraint(condition=models.Q(('wskaznik_zmiennosci__gte', 0), ('wskaznik_zmiennosci__lte', 1)), name='wskaznik_zmiennosci_w_zakresie')],
            },
        ),
    ]
